### ISSUE TITLE
ebpf_exporter show fatal error: unexpected signal during runtime execution

### ISSUE THREAD

**Issue by qls152** [cloudflare/ebpf_exporter#101]
I try to write https://github.com/iovisor/bcc/blob/master/tools/tcpconnect.py in `ebpf_exporter` as follow:

```yaml
programs:
  - name: tcpconn
    metrics:
      counters:
        - name: data4
          help: tcp4 connection latency
          table: ipv4_count
          labels:
            - name: source_addr
              size: 4
              decoders:
                - name: uint
            - name: dst_addr
              size: 4
              decoders:
                - name: uint
            - name: dst_port
              size: 2
              decoders:
                - name: uint
          help: tcp6 connection latency
          table: ipv6_count
          labels:
            - name: source_addr
              size: 16
              decoders:
                - name: uint
            - name: dst_addr
              size: 16
              decoders:
                - name: uint
            - name: dst_port
              size: 2
              decoders:
                - name: uint
    kprobes:
      tcp_v4_connect: trace_connect_entry
      tcp_v6_connect: trace_connect_entry
    
    kretprobes:
      tcp_v4_connect: trace_connect_v4_return
      tcp_v6_connect: trace_connect_v6_return
    code: |
      #include <uapi/linux/ptrace.h>
      #include <net/sock.h>
      #include <net/tcp_states.h>
      #include <bcc/proto.h>

      BPF_HASH(currsock, u32, struct sock *);
      
      struct ipv4_flow_key_t {
        u32 saddr;
        u32 daddr;
        u16 dport;
      };
      BPF_HASH(ipv4_count, struct ipv4_flow_key_t);
      struct ipv6_flow_key_t {
        unsigned __int128 saddr;
        unsigned __int128 daddr;
        u16 dport;
      };
      BPF_HASH(ipv6_count, struct ipv6_flow_key_t);

      int trace_connect_entry(struct pt_regs *ctx, struct sock *sk) {

        u64 pid_tgid = bpf_get_current_pid_tgid();
        u32 tid = pid_tgid;
     
        // stash the sock ptr for lookup on return
        currsock.update(&tid, &sk);
        return 0;
      };

      static int trace_connect_return(struct pt_regs *ctx, short ipver) {
        int ret = PT_REGS_RC(ctx);
        u64 pid_tgid = bpf_get_current_pid_tgid();
        u32 pid = pid_tgid >> 32;
        u32 tid = pid_tgid;
        struct sock **skpp;
        skpp = currsock.lookup(&tid);
        if (skpp == 0) {
          return 0;   // missed entry
        }
        if (ret != 0) {
          // failed to send SYNC packet, may not have populated
          // socket __sk_common.{skc_rcv_saddr, ...}
          currsock.delete(&tid);
          return 0;
        }
        // pull in details
        struct sock *skp = *skpp;
        u16 lport = skp->__sk_common.skc_num;
        u16 dport = skp->__sk_common.skc_dport;
        // FILTER_PORT
        if (ipver == 4) {
          struct ipv4_flow_key_t flow_key = {};
          flow_key.saddr = skp->__sk_common.skc_rcv_saddr;
          flow_key.daddr = skp->__sk_common.skc_daddr;
          flow_key.dport = ntohs(dport);
          ipv4_count.increment(flow_key);
        } else /* 6 */ {
          struct ipv6_flow_key_t flow_key = {};
          bpf_probe_read_kernel(&flow_key.saddr, sizeof(flow_key.saddr),
              skp->__sk_common.skc_v6_rcv_saddr.in6_u.u6_addr32);
          bpf_probe_read_kernel(&flow_key.daddr, sizeof(flow_key.daddr),
              skp->__sk_common.skc_v6_daddr.in6_u.u6_addr32);
          flow_key.dport = ntohs(dport);
          ipv6_count.increment(flow_key);
        }
        currsock.delete(&tid);
        return 0;
      }
      int trace_connect_v4_return(struct pt_regs *ctx) {
        return trace_connect_return(ctx, 4);
      }
      int trace_connect_v6_return(struct pt_regs *ctx) {
        return trace_connect_return(ctx, 6);
      }
```

when I check result by curl localhost:9435/metrics, ebpf_exporter core as follow

```
2021/03/26 02:33:13 Listening on :9435
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x7f524950c845]

runtime stack:
runtime.throw(0xa40fb8, 0x2a)
	/usr/lib/golang/src/runtime/panic.go:1116 +0x72
runtime.sigpanic()
	/usr/lib/golang/src/runtime/signal_unix.go:701 +0x46a

goroutine 22 [syscall]:
runtime.cgocall(0x9037d0, 0xc00005d6a0, 0x7f524d55ae98)
	/usr/lib/golang/src/runtime/cgocall.go:133 +0x5b fp=0xc00005d670 sp=0xc00005d638 pc=0x4095ab
github.com/iovisor/gobpf/bcc._Cfunc_bpf_table_key_snprintf(0x2f27680, 0x2, 0xc0000f4180, 0x180, 0xc00021c060, 0x0)
	_cgo_gotypes.go:918 +0x4d fp=0xc00005d6a0 sp=0xc00005d670 pc=0x7313cd
github.com/iovisor/gobpf/bcc.(*Table).KeyBytesToStr.func1(0xc000097000, 0xc0000f4180, 0xc0000f4180, 0x180, 0x180, 0xc00021c060, 0xc00005d748)
	/home/qinliansong/data/pkg/mod/github.com/iovisor/gobpf@v0.1.1/bcc/table.go:117 +0xaf fp=0xc00005d6f0 sp=0xc00005d6a0 pc=0x73aa0f
github.com/iovisor/gobpf/bcc.(*Table).KeyBytesToStr(0xc000097000, 0xc00021c060, 0x30, 0x30, 0x2, 0x1, 0xc00002a120, 0xa3047b)
	/home/qinliansong/data/pkg/mod/github.com/iovisor/gobpf@v0.1.1/bcc/table.go:117 +0x96 fp=0xc00005d758 sp=0xc00005d6f0 pc=0x7372d6
github.com/cloudflare/ebpf_exporter/exporter.(*Exporter).tableValues(0xc0000aa3c0, 0xc0000c8a00, 0xc0000c67b0, 0xa, 0xc0000e4240, 0x3, 0x3, 0xc00014e310, 0xffffffffffffff00, 0x39, ...)
	/home/qinliansong/data/pkg/mod/github.com/cloudflare/ebpf_exporter@v1.2.3/exporter/exporter.go:244 +0x14f fp=0xc00005d888 sp=0xc00005d758 pc=0x8557ef
github.com/cloudflare/ebpf_exporter/exporter.(*Exporter).collectCounters(0xc0000aa3c0, 0xc0000a87e0)
	/home/qinliansong/data/pkg/mod/github.com/cloudflare/ebpf_exporter@v1.2.3/exporter/exporter.go:151 +0x228 fp=0xc00005dbf0 sp=0xc00005d888 pc=0x854628
github.com/cloudflare/ebpf_exporter/exporter.(*Exporter).Collect(0xc0000aa3c0, 0xc0000a87e0)
	/home/qinliansong/data/pkg/mod/github.com/cloudflare/ebpf_exporter@v1.2.3/exporter/exporter.go:143 +0x3a4 fp=0xc00005ded8 sp=0xc00005dbf0 pc=0x8541f4
github.com/prometheus/client_golang/prometheus.(*Registry).Gather.func1()
	/home/qinliansong/data/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:446 +0x19d fp=0xc00005dfe0 sp=0xc00005ded8 pc=0x85098d
runtime.goexit()
	/usr/lib/golang/src/runtime/asm_amd64.s:1373 +0x1 fp=0xc00005dfe8 sp=0xc00005dfe0 pc=0x4694c1
created by github.com/prometheus/client_golang/prometheus.(*Registry).Gather
	/home/qinliansong/data/pkg/mod/github.com/prometheus/client_golang@v1.10.0/prometheus/registry.go:457 +0x599

```

I'm not very good at go， So I would like to ask why this problem occurs？

**Comment by bobrik** [comment]
I can see a few issues:

* `ipv6_count` is not assigned to a separate metric (missing `- name` line)
* `ipv4_count` struct seems to have padding on my arm64 machine, so `dst_port` needs to have `size: 4`
* `size: 16` probably doesn't make sense, since Go doesn't support `u128`

I suggest you upgrade to the latest BCC as well. You might want to make it work on IPv4 first and then expand to IPv4.

I'm going to close it, since it's been a while.
