### ISSUE TITLE
panic in cgroup decoder.

### ISSUE THREAD

**Issue by bwplotka** [cloudflare/ebpf_exporter#107]
Hi,

When running ebpf_exporter in the dockerized environment I got this panic after couple of errors:

```
15:37:49 ebpf_exporter: 2021/09/14 13:37:49 Error refreshing cgroup id to path map: lstat /sys/fs/cgroup/unified/system.slice/system-openvpn.slice/openvpn@ovpn-fab-udp.service: no such file or directory
15:37:54 ebpf_exporter: 2021/09/14 13:37:54 Error refreshing cgroup id to path map: open /sys/fs/cgroup/unified/system.slice/system-openvpn.slice/openvpn@ovpn-ams2-tcp.service: no such file or directory
15:38:04 ebpf_exporter: 2021/09/14 13:38:04 Error refreshing cgroup id to path map: readdirent /sys/fs/cgroup/unified/system.slice/system-openvpn.slice/openvpn@ovpn-pnq2-tcp.service: no such file or directory
15:38:10 ebpf_exporter: 2021/09/14 13:38:10 Error refreshing cgroup id to path map: lstat /sys/fs/cgroup/unified/system.slice/system-openvpn.slice/openvpn@ovpn-pek2-tcp.service/cgroup.freeze: no such file or directory
15:38:57 ebpf_exporter: 2021/09/14 13:38:57 Error refreshing cgroup id to path map: lstat /sys/fs/cgroup/unified/system.slice/system-openvpn.slice/openvpn@ovpn-rdu2-udp.service/cgroup.max.depth: no such file or directory
15:38:57 ebpf_exporter: 2021/09/14 13:38:57 Error resolving handle of /sys/fs/cgroup/unified/system.slice/system-openvpn.slice/openvpn@ovpn-tlv-tcp.service: no such file or directory
15:38:57 ebpf_exporter: panic: runtime error: invalid memory address or nil pointer dereference
15:38:57 ebpf_exporter: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6e51dc]
15:38:57 ebpf_exporter: goroutine 691 [running]:
15:38:57 ebpf_exporter: golang.org/x/sys/unix.(*FileHandle).Size(...)
15:38:57 ebpf_exporter: /root/ebpf_exporter/vendor/golang.org/x/sys/unix/syscall_linux.go:2309
15:38:57 ebpf_exporter: golang.org/x/sys/unix.(*FileHandle).Bytes(...)
15:38:57 ebpf_exporter: /root/ebpf_exporter/vendor/golang.org/x/sys/unix/syscall_linux.go:2312
15:38:57 ebpf_exporter: github.com/cloudflare/ebpf_exporter/decoder.(*CGroup).refreshCache.func1(0xc000742c60, 0x55, 0xa2db50, 0xc000172ea0, 0x0, 0x0, 0x0, 0xc000172ea0)
15:38:57 ebpf_exporter: /root/ebpf_exporter/decoder/cgroup.go:68 +0xdc
15:38:57 ebpf_exporter: path/filepath.walk(0xc000742c60, 0x55, 0xa2db50, 0xc000172ea0, 0xc000693600, 0x0, 0x0)
15:38:57 ebpf_exporter: /usr/lib/go-1.16/src/path/filepath/path.go:418 +0xe7
15:38:57 ebpf_exporter: path/filepath.walk(0xc0006a7a80, 0x38, 0xa2db50, 0xc000172270, 0xc000693600, 0x0, 0x0)
15:38:57 ebpf_exporter: /usr/lib/go-1.16/src/path/filepath/path.go:438 +0x31b
15:38:57 ebpf_exporter: path/filepath.walk(0xc0005528d0, 0x23, 0xa2db50, 0xc00057b6c0, 0xc000693600, 0x0, 0x0)
15:38:57 ebpf_exporter: /usr/lib/go-1.16/src/path/filepath/path.go:438 +0x31b
15:38:57 ebpf_exporter: path/filepath.walk(0x991a03, 0x16, 0xa2db50, 0xc00057a0d0, 0xc000693600, 0x0, 0xa2db50)
15:38:57 ebpf_exporter: /usr/lib/go-1.16/src/path/filepath/path.go:438 +0x31b
15:38:57 ebpf_exporter: path/filepath.Walk(0x991a03, 0x16, 0xc000693600, 0xc000066100, 0x0)
15:38:57 ebpf_exporter: /usr/lib/go-1.16/src/path/filepath/path.go:501 +0x113
15:38:57 ebpf_exporter: github.com/cloudflare/ebpf_exporter/decoder.(*CGroup).refreshCache(0xc000010400, 0xc000204690, 0x70248e)
15:38:57 ebpf_exporter: /root/ebpf_exporter/decoder/cgroup.go:54 +0xfc
15:38:57 ebpf_exporter: github.com/cloudflare/ebpf_exporter/decoder.(*CGroup).Decode(0xc000010400, 0xc0005a6478, 0x7, 0x8, 0xc00002b5e8, 0x6, 0xc0001bb620, 0xd39dd8, 0x0, 0x0, ...)
15:38:57 ebpf_exporter: /root/ebpf_exporter/decoder/cgroup.go:35 +0xd4
15:38:57 ebpf_exporter: github.com/cloudflare/ebpf_exporter/decoder.(*Set).Decode(0xc0001dec80, 0xc000200ae0, 0x8, 0x8, 0xc00002b570, 0x6, 0x8, 0xc0001d8a80, 0x2, 0x2, ...)
15:38:57 ebpf_exporter: /root/ebpf_exporter/decoder/decoder.go:54 +0x1f6
15:38:57 ebpf_exporter: github.com/cloudflare/ebpf_exporter/decoder.(*Set).DecodeLabels(0xc0001dec80, 0xc000200ae0, 0x8, 0x8, 0xc0001bb590, 0x1, 0x1, 0x0, 0x1, 0x1, ...)
15:38:57 ebpf_exporter: /root/ebpf_exporter/decoder/decoder.go:97 +0x1fd
15:38:57 ebpf_exporter: github.com/cloudflare/ebpf_exporter/exporter.(*Exporter).tableValues
```

I don't have time to help to fix it now, so putting here for helpful contributors (: Help wanted!

Repro: See this e2e test in a for of common Go unit test: https://github.com/thanos-community/ebpf-instrumentation/blob/4fc84f9eb103fd31ed833eafc9d581115ad12b21/examples/ebpf_test.go
Dockefile: https://github.com/thanos-community/ebpf-instrumentation/blob/4fc84f9eb103fd31ed833eafc9d581115ad12b21/exporter/Dockerfile

**Comment by bwplotka** [comment]
Actually.. fix was easy: https://github.com/cloudflare/ebpf_exporter/issues/107
